"""
arrival_models.py - mathematical arrival / workload models (pure Python, seeded).

Every run first builds a TRACE: the complete list of planned arrivals for the run,
generated from a mathematical model. The Locust driver then replays it in real time
(open model: arrivals do not wait for responses). The trace is saved with the run,
so the offered load is known exactly ("ground truth"), independently of how the
cluster responded.

Models (see README.md for the formulas):
  nhpp   : Non-Homogeneous Poisson Process, lambda(t) sinusoidal, generated by thinning
  mmpp   : Markov Modulated Poisson Process, continuous-time Markov chain over states,
           exponential sojourn times, Poisson arrivals with a per-state rate
  pareto : homogeneous Poisson session arrivals, per-session work size ~ Bounded Pareto
  onoff  : N independent ON/OFF sources, heavy-tailed (Bounded Pareto) ON and OFF periods,
           Poisson requests while ON -> aggregate traffic is self-similar

Python >= 3.8, no third-party dependency (runs inside the Locust venv on node-loadgen).
"""
import csv
import json
import math
import os
import random

# ----------------------------------------------------------------------------- distributions


def exponential(rng, mean):
    return rng.expovariate(1.0 / mean)


def geometric(rng, mean):
    """Number of trials >= 1 with E = mean (memoryless session length)."""
    p = 1.0 / mean
    return 1 + int(math.log(1.0 - rng.random()) / math.log(1.0 - p)) if p < 1 else 1


def bounded_pareto(rng, alpha, low, high):
    """Inverse-CDF sample of Bounded Pareto(alpha, L, H):
    F(x) = (1 - (L/x)^a) / (1 - (L/H)^a),  L <= x <= H."""
    u = rng.random()
    return low / (1.0 - u * (1.0 - (low / high) ** alpha)) ** (1.0 / alpha)


def bounded_pareto_mean(alpha, low, high):
    if abs(alpha - 1.0) < 1e-12:
        return high * low / (high - low) * math.log(high / low)
    la, ha = low ** alpha, high ** alpha
    return ha * la / (ha - la) * alpha / (alpha - 1.0) * (1.0 / low ** (alpha - 1.0) - 1.0 / high ** (alpha - 1.0))


def bounded_pareto_ceil_mean(alpha, low, high):
    """E[ceil(X)] = sum_{k>=0} P(X > k) for integer work sizes (cart items)."""
    def sf(x):
        if x < low:
            return 1.0
        if x >= high:
            return 0.0
        return ((low / x) ** alpha - (low / high) ** alpha) / (1.0 - (low / high) ** alpha)
    return sum(sf(k) for k in range(int(math.ceil(high)) + 1))


def poisson_times(rng, rate, start, end):
    """Homogeneous Poisson process on [start, end): exponential inter-arrival times."""
    out, t = [], start
    if rate <= 0:
        return out
    while True:
        t += rng.expovariate(rate)
        if t >= end:
            return out
        out.append(t)


def nhpp_times(rng, rate_fn, rate_max, start, end):
    """Lewis-Shedler thinning: candidates from Poisson(rate_max), keep t with prob rate_fn(t)/rate_max."""
    out = []
    for t in poisson_times(rng, rate_max, start, end):
        if rng.random() * rate_max <= rate_fn(t):
            out.append(t)
    return out


def ctmc_path(rng, states, transitions, initial, duration):
    """Continuous-time Markov chain: [(t_start, t_end, state), ...] covering [0, duration).
    Sojourn in state s ~ Exp(mean_sojourn[s]); next state drawn from transitions[s]."""
    path, t, s = [], 0.0, initial
    while t < duration:
        stay = exponential(rng, states[s]['mean_sojourn'])
        path.append((t, min(t + stay, duration), s))
        t += stay
        nxt, probs = zip(*transitions[s].items())
        s = rng.choices(nxt, weights=probs)[0]
    return path


# ----------------------------------------------------------------------------- scenario configs
def nhpp_rate(cfg, phase):
    """lambda(t) in sessions/s: base + A1 sin(2 pi t / T + phase) + A2 sin(4 pi t / T + 2 phase), >= floor."""
    T = cfg['period_sec']

    def rate(t):
        v = (cfg['base'] + cfg['amp1'] * math.sin(2 * math.pi * t / T + phase)
             + cfg['amp2'] * math.sin(4 * math.pi * t / T + 2 * phase))
        return max(cfg['floor'], v)
    return rate


def requests_per_session(cfg):
    """Expected HTTP requests generated by one session (to convert sessions/s into rps)."""
    if cfg['model'] == 'pareto':
        p = cfg['items']
        return 3.0 + bounded_pareto_ceil_mean(p['alpha'], p['low'], p['high'])   # home + items + cart + checkout
    return 1.0 + cfg['mean_actions']                                        # home + K actions


def build_trace(cfg, duration, seed):
    """All planned arrivals of one run.
    events: dict(t, kind, source, size, state) sorted by t
        kind='session' (nhpp, mmpp, pareto): size = number of actions (or cart items for pareto)
        kind='request' (onoff): one request from persistent client `source`
    rate  : per-second designed load: dict(t, state, lambda_sessions, expected_rps)"""
    rng = random.Random(seed)
    model = cfg['model']
    events, rate = [], []

    if model in ('nhpp', 'mmpp', 'pareto'):
        rps_per_session = requests_per_session(cfg)
        if model == 'nhpp':
            phase = rng.uniform(0, 2 * math.pi) if cfg.get('random_phase', True) else 0.0
            fn = nhpp_rate(cfg, phase)
            rate_max = cfg['base'] + abs(cfg['amp1']) + abs(cfg['amp2'])
            times = [(t, 'nhpp') for t in nhpp_times(rng, fn, rate_max, 0.0, duration)]
            rate = [{'t': s, 'state': 'nhpp', 'lambda_sessions': fn(s)} for s in range(duration)]
            meta = {'phase': phase}
        elif model == 'mmpp':
            path = ctmc_path(rng, cfg['states'], cfg['transitions'], cfg['initial'], duration)
            times = []
            for a, b, s in path:
                times += [(t, s) for t in poisson_times(rng, cfg['states'][s]['rate'], a, b)]
            seg = iter(path)
            cur = next(seg)
            for s in range(duration):
                while s >= cur[1]:
                    cur = next(seg)
                rate.append({'t': s, 'state': cur[2], 'lambda_sessions': cfg['states'][cur[2]]['rate']})
            meta = {'path': [[round(a, 3), round(b, 3), s] for a, b, s in path]}
        else:
            times = [(t, 'poisson') for t in poisson_times(rng, cfg['session_rate'], 0.0, duration)]
            rate = [{'t': s, 'state': 'poisson', 'lambda_sessions': cfg['session_rate']} for s in range(duration)]
            meta = {}
        for i, (t, state) in enumerate(times):
            if model == 'pareto':
                p = cfg['items']
                size = int(math.ceil(bounded_pareto(rng, p['alpha'], p['low'], p['high'])))
            else:
                size = geometric(rng, cfg['mean_actions'])
            events.append({'t': t, 'kind': 'session', 'source': i, 'size': size, 'state': state})
        for r in rate:
            r['expected_rps'] = r['lambda_sessions'] * rps_per_session

    elif model == 'onoff':
        on, off = cfg['on'], cfg['off']
        warmup = cfg.get('warmup_sec', 600)        # simulate before t=0 so sources start in steady state
        on_count = [0] * duration
        for src in range(cfg['n_sources']):
            t = -float(warmup)
            is_on = rng.random() < 0.5
            while t < duration:
                d = (bounded_pareto(rng, on['alpha'], on['low'], on['high']) if is_on
                     else bounded_pareto(rng, off['alpha'], off['low'], off['high']))
                if is_on:
                    a, b = max(t, 0.0), min(t + d, duration)
                    if b > a:
                        for tt in poisson_times(rng, cfg['rate_on'], a, b):
                            events.append({'t': tt, 'kind': 'request', 'source': src, 'size': 1, 'state': 'on'})
                        for s in range(int(math.ceil(a)), int(math.ceil(b))):
                            if s < duration:
                                on_count[s] += 1
                t += d
                is_on = not is_on
        rate = [{'t': s, 'state': f'on={on_count[s]}', 'lambda_sessions': float(on_count[s]),
                 'expected_rps': on_count[s] * cfg['rate_on']} for s in range(duration)]
        meta = {}
    else:
        raise ValueError(f'unknown model {model}')

    events.sort(key=lambda e: e['t'])
    return {'model': model, 'seed': seed, 'duration': duration, 'events': events, 'rate': rate,
            'meta': meta, 'expected_mean_rps': expected_mean_rps(cfg),
            'designed_mean_rps': sum(r['expected_rps'] for r in rate) / max(1, len(rate))}


def expected_mean_rps(cfg):
    """Long-run mean request rate implied by the model parameters (for calibration)."""
    m = cfg['model']
    if m == 'nhpp':
        return max(cfg['floor'], cfg['base']) * requests_per_session(cfg)   # sine terms average to 0
    if m == 'mmpp':
        # stationary distribution of the CTMC: pi_s ∝ v_s * mean_sojourn_s, v = embedded-chain stationary
        names = list(cfg['states'])
        v = {s: 1.0 / len(names) for s in names}
        for _ in range(500):
            v = {s: sum(v[r] * cfg['transitions'][r].get(s, 0.0) for r in names) for s in names}
        w = {s: v[s] * cfg['states'][s]['mean_sojourn'] for s in names}
        z = sum(w.values())
        return sum(w[s] / z * cfg['states'][s]['rate'] for s in names) * requests_per_session(cfg)
    if m == 'pareto':
        return cfg['session_rate'] * requests_per_session(cfg)
    on = bounded_pareto_mean(cfg['on']['alpha'], cfg['on']['low'], cfg['on']['high'])
    off = bounded_pareto_mean(cfg['off']['alpha'], cfg['off']['low'], cfg['off']['high'])
    return cfg['n_sources'] * on / (on + off) * cfg['rate_on']


def theoretical_hurst(cfg):
    """ON/OFF with Pareto tails: H = (3 - alpha_min) / 2 (Taqqu, Willinger & Sherman 1997)."""
    a = min(cfg['on']['alpha'], cfg['off']['alpha'])
    return (3 - a) / 2 if 1 < a < 2 else 0.5


def write_trace(trace, out_dir):
    os.makedirs(out_dir, exist_ok=True)
    with open(os.path.join(out_dir, 'arrival_trace.csv'), 'w', newline='') as f:
        w = csv.writer(f)
        w.writerow(['t', 'kind', 'source', 'size', 'state'])
        for e in trace['events']:
            w.writerow([round(e['t'], 4), e['kind'], e['source'], e['size'], e['state']])
    with open(os.path.join(out_dir, 'designed_rate.csv'), 'w', newline='') as f:
        w = csv.writer(f)
        w.writerow(['t', 'state', 'lambda_sessions', 'expected_rps'])
        for r in trace['rate']:
            w.writerow([r['t'], r['state'], round(r['lambda_sessions'], 5), round(r['expected_rps'], 5)])
    summary = {k: trace[k] for k in ('model', 'seed', 'duration', 'meta', 'expected_mean_rps', 'designed_mean_rps')}
    summary['n_events'] = len(trace['events'])
    with open(os.path.join(out_dir, 'trace_meta.json'), 'w') as f:
        json.dump(summary, f, indent=1)
